import Head from "next/head";
import Image from "next/image";
import Admin from "./Admin/Admin";
import Login from "./Login/Login";
import User from "./User/User";
Admin;
export default function Home() {
  return (
    <>
      <Head>
        <title>onboarding test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="/build/tailwind.css"
          type="text/css"
          media="screen"
          title="no title"
          charSet="utf-8"
        />
      </Head>

      {/* <Login /> */}
      <Admin />
      {/* <User /> */}
    </>
  );
}
